[[redirects]]
    from = "/login"
    to = "https://www.api.planbic.de/auth/login"
    status = 200
    force = true

[[redirects]]
    from = "/auth"
    to = "https://coderjana3.netlify.app/auth" 

